FROM pytorch/pytorch:2.9.0-cuda12.6-cudnn9-devel

ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt update && apt install -y \
    ffmpeg \
    libx264-dev \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \ 
    libswscale-dev \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libtbb-dev \
    libjpeg-turbo8-dev \
    libpng-dev \
    libtiff-dev \
    libgoogle-perftools-dev \
    libglib2.0-0 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc.so"

# Set the working directory
WORKDIR /app

# Copy requirements and install Python dependencies
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy project structure (filtered by ./.dockerignore)
COPY . .

# Set permissions for entire /app directory at once
RUN chmod -R 777 /app

ENV \
    FPS="30"\
    ALERTS_COOLDOWN_SECONDS="1.0"\
    POISON_PILL_TIMEOUT="5.0"\
    SHUTDOWN_TIMEOUT="10.0"\
    SAFETY_RADIUS_M="2.0"\
    SLOPE_ANGLE_THRESHOLD="30.0"\
    GEOFENCING_VERTEXES="not_specified"\
    SLIDING_WINDOW_SIZE_S="30.0"\
    DRONE_TRUE_FOCAL_LEN_MM="12.29"\
    DRONE_SENSOR_WIDTH_MM="17.35"\
    DRONE_SENSOR_HEIGHT_MM="13.00"\
    DRONE_SENSOR_WIDTH_PIXELS="5280"\
    DRONE_SENSOR_HEIGHT_PIXELS="3956"\
    MAX_SIZE_FRAME_READER_OUT="3"\
    MAX_SIZE_TELEMETRY_READER_OUT="20"\
    MAX_SIZE_DETECTION_IN="3"\
    MAX_SIZE_SEGMENTATION_IN="3"\
    MAX_SIZE_GEO_IN="3"\
    MAX_SIZE_DETECTION_RESULTS="3"\
    MAX_SIZE_SEGMENTATION_RESULTS="3"\
    MAX_SIZE_GEO_RESULTS="3"\
    MAX_SIZE_MODELS_ALIGNMENT_RESULTS="6"\
    MAX_SIZE_DANGER_DETECTION_RESULT="3"\
    MAX_SIZE_VIDEO_STREAM="3"\
    MAX_SIZE_NOTIFICATIONS_STREAM="5"\
    MAX_SIZE_VIDEO_STORAGE="3"\
    VIDEO_STREAM_READER_USERNAME="not_specified"\
    VIDEO_STREAM_READER_PASSWORD="not_specified"\
    VIDEO_STREAM_READER_HOST="0.0.0.0"\
    VIDEO_STREAM_READER_PROTOCOL="rtsp"\
    VIDEO_STREAM_READER_PORT="8554"\
    VIDEO_STREAM_READER_STREAM_KEY="drone"\
    VIDEO_STREAM_READER_CONNECTION_OPEN_TIMEOUT_S="5.0"\
    VIDEO_STREAM_READER_RECONNECT_DELAY="5.0"\
    VIDEO_STREAM_READER_MAX_CONSECUTIVE_CONNECTION_FAILURES="5"\
    VIDEO_STREAM_READER_FRAME_READ_TIMEOUT_S="0.05"\
    VIDEO_STREAM_READER_FRAME_RETRY_DELAY="0.05"\
    VIDEO_STREAM_READER_FRAME_MAX_CONSECUTIVE_FAILURES="30"\
    VIDEO_STREAM_READER_BUFFER_SIZE="1"\
    VIDEO_STREAM_READER_QUEUE_PUT_TIMEOUT="0.02"\
    TELEMETRY_LISTENER_USERNAME="not_specified"\
    TELEMETRY_LISTENER_PASSWORD="not_specified"\
    TELEMETRY_LISTENER_HOST="0.0.0.0"\
    TELEMETRY_LISTENER_PROTOCOL="mqtt"\
    TELEMETRY_LISTENER_PORT="1883"\
    TELEMETRY_LISTENER_QOS_LEVEL="1"\
    TELEMETRY_LISTENER_RECONNECT_DELAY="5.0"\
    TELEMETRY_LISTENER_MSG_WAIT_TIMEOUT="1.0"\
    TELEMETRY_LISTENER_MAX_INCOMING_MESSAGES="100"\
    FRAMETELCOMB_MAX_TELEM_BUFFER_SIZE="40"\
    FRAMETELCOMB_MAX_TIME_DIFF="0.15"\
    FRAMETELCOMB_QUEUE_GET_TIMEOUT="0.01"\
    FRAMETELCOMB_QUEUE_PUT_MAX_RETRIES="3"\
    FRAMETELCOMB_QUEUE_PUT_BACKOFF="0.005"\
    MODELS_QUEUE_GET_TIMEOUT="0.02"\
    MODELS_QUEUE_PUT_TIMEOUT="0.02"\
    ANNOTATION_QUEUE_GET_TIMEOUT="0.02"\
    ANNOTATION_QUEUE_PUT_TIMEOUT="0.02"\
    ANNOTATION_MAX_PUT_ALERT_CONSECUTIVE_FAILURES="3"\
    ANNOTATION_MAX_PUT_VIDEO_CONSECUTIVE_FAILURES="60"\
    ALERTS_QUEUE_GET_TIMEOUT="0.1"\
    ALERTS_MAX_CONSECUTIVE_FAILURES="5"\
    ALERTS_JPEG_COMPRESSION_QUALITY="85"\
    WEBSOCKET_HOST="localhost"\
    WEBSOCKET_PORT="8443"\
    WS_MANAGER_BROADCAST_TIMEOUT="2.0"\
    WS_MANAGER_PING_INTERVAL="5.0"\
    WS_MANAGER_PING_TIMEOUT="20.0"\
    WS_MANAGER_THREAD_CLOSE_TIMEOUT="5.0"\
    DB_USERNAME="not_specified"\
    DB_PASSWORD="not_specified"\
    DB_HOST="0.0.0.0"\
    DB_SERVICE="not_specified"\
    DB_PORT="5432"\
    DB_MANAGER_QUEUE_SIZE="5"\
    DB_MANAGER_POOL_SIZE="5"\
    DB_MANAGER_MAX_OVERFLOW="10"\
    DB_MANAGER_QUEUE_WAIT_TIMEOUT="0.1"\
    DB_MANAGER_THREAD_CLOSE_TIMEOUT="5.0"\
    VIDEO_WRITER_GET_FRAME_TIMEOUT="0.01"\
    VIDEO_WRITER_HANDOFF_TIMEOUT="1.0"\
    VIDEO_OUT_STREAM_USERNAME="not_specified"\
    VIDEO_OUT_STREAM_PASSWORD="not_specified"\
    VIDEO_OUT_STREAM_HOST="0.0.0.0"\
    VIDEO_OUT_STREAM_PROTOCOL="rtmp"\
    VIDEO_OUT_STREAM_PORT="1935"\
    VIDEO_OUT_STREAM_STREAM_KEY="annot"\
    VIDEO_OUT_STREAM_QUEUE_GET_TIMEOUT="0.01"\
    VIDEO_OUT_STREAM_FFMPEG_STARTUP_TIMEOUT="0.5"\
    VIDEO_OUT_STREAM_FFMPEG_SHUTDOWN_TIMEOUT="8.0"\
    VIDEO_OUT_STREAM_STARTUP_TIMEOUT="2.0"\
    VIDEO_OUT_STREAM_SHUTDOWN_TIMEOUT="5.0"\
    VIDEO_OUT_STORE_USERNAME="not_specified"\
    VIDEO_OUT_STORE_PASSWORD="not_specified"\
    VIDEO_OUT_STORE_HOST="0.0.0.0"\
    VIDEO_OUT_STORE_SERVICE="azure"\
    VIDEO_OUT_STORE_PORT="8443"\
    VIDEO_OUT_STORE_DELETE_LOCAL_ON_SUCCESS="True"\
    VIDEO_OUT_STORE_QUEUE_GET_TIMEOUT="3.0"\
    VIDEO_OUT_STORE_MAX_UPLOAD_RETRIES="3"\
    VIDEO_OUT_STORE_RETRY_BACKOFF_TIME="5.0"

# open https port for ui to connect to websocket server (alerts)
EXPOSE 8443

# Set entrypoint
ENTRYPOINT ["python", "main.py"]