services:

  db-writer:
    build:
      context: .
      dockerfile: db_writer/Dockerfile
    env_file: db_writer/.env
    networks:
      - internal
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - internal
    ports:
      - "8443:8443"
    shm_size: "256m"
    depends_on:
      - db-writer
    restart: unless-stopped

networks:
  internal:
    driver: bridge
